name = "ApproxFunFourier"
uuid = "59844689-9c9d-51bf-9583-5b794ec66d30"
version = "0.2.5"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
ApproxFunBase = "fbd15aa5-315a-5a7d-a8a4-24992e37be05"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastTransforms = "057dd010-8810-581a-b7be-e3fc3b93f78c"
InfiniteArrays = "4858937d-0d70-526a-a4dd-2d5cb5dd786c"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
AbstractFFTs = "0.5"
ApproxFunBase = "0.3.4"
DomainSets = "0.3"
FFTW = "1.1"
FastTransforms = "0.10"
InfiniteArrays = "0.5, 0.6, 0.7, 0.8"
IntervalSets = "0.5"
Reexport = "0.2"
SpecialFunctions = "0.8, 0.9, 0.10"
julia = "1.3"

[extras]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SpecialFunctions"]
